version: '3.8'
services:
  mongodb:
    image: 'mongo'
    ports: 
      - "14017:27017"
    # restart: 'always'
    environment:
      MONGO_INITDB_ROOT_USERNAM: ${MONGO_ADMIN_NAME}
      MONGO_INTIDB_ROOT_PASSWORD: ${MONGO_ADMIN_SECRET}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-data: